project_id = "hrxreyncncmqzcyyqnpe"

[functions.generate-answer]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.read-to-me]
verify_jwt = false

[functions.create-promo-code]
verify_jwt = false