import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import FloatingBubbles from "@/components/FloatingBubbles";
import { Mail } from "lucide-react";

const termsSections = [
  {
    title: "1. Acceptance of Terms",
    content: (
      <>
        <p>By accessing or using the Little Minds BIG Questions website, you agree to these Terms and Conditions.</p>
        <p>If you do not agree with these terms, you should not use the platform.</p>
        <p>These terms apply to all users of the website, including visitors and paid subscribers.</p>
      </>
    ),
  },
  {
    title: "2. Purpose of the Platform",
    content: (
      <>
        <p>Little Minds BIG Questions provides storytelling tools designed to help parents and caregivers explain complex topics to children using metaphor and narrative.</p>
        <p>Content generated on this platform is intended to support family conversations and should not be considered professional advice.</p>
        <p className="italic text-muted-foreground">The platform does not provide medical, psychological, or therapeutic guidance.</p>
      </>
    ),
  },
  {
    title: "3. User Eligibility",
    content: (
      <>
        <p>The platform is intended for use by parents, guardians, or caregivers.</p>
        <p>Children under the age of 13 should not create accounts or submit information directly.</p>
        <p>Parents are responsible for supervising how content is shared with their children.</p>
      </>
    ),
  },
  {
    title: "4. User Submissions",
    content: (
      <>
        <p>Users may submit questions asked by children.</p>
        <p>Users agree not to submit:</p>
        <ul className="list-disc pl-6 space-y-1">
          <li>offensive or harmful content</li>
          <li>identifying personal information beyond a child's first name</li>
          <li>unlawful or abusive material</li>
        </ul>
        <p>Submitted questions may be stored on the platform to generate stories.</p>
        <p>If the user selects the public option, the question and generated response may appear in the public question library.</p>
      </>
    ),
  },
  {
    title: "5. AI Generated Content",
    content: (
      <>
        <p>Responses generated by Little Minds BIG Questions are created using artificial intelligence.</p>
        <p>While we aim to produce thoughtful and supportive responses, the content is generated automatically and may not always be perfect.</p>
        <p>Parents and caregivers should review generated responses before sharing them with children.</p>
      </>
    ),
  },
  {
    title: "6. Paid Access Features",
    content: (
      <>
        <p>Some features of the platform require a $10 payment.</p>
        <p>These features currently include:</p>
        <ul className="list-disc pl-6 space-y-1">
          <li>saving questions to a private library</li>
          <li>read-aloud audio functionality</li>
          <li>downloadable digital content</li>
        </ul>
        <p>Access to these features may evolve as the platform develops.</p>
      </>
    ),
  },
  {
    title: "7. Future Products",
    content: (
      <>
        <p>In the future, Little Minds BIG Questions may offer additional products including:</p>
        <ul className="list-disc pl-6 space-y-1">
          <li>personalised printed books based on a child's questions</li>
          <li>downloadable story collections</li>
          <li>educational resources for families</li>
        </ul>
        <p>These products may be subject to separate purchase terms.</p>
      </>
    ),
  },
  {
    title: "8. Intellectual Property",
    content: (
      <>
        <p>All content, branding, illustrations, and design elements on this website are the property of Little Minds BIG Questions unless otherwise stated.</p>
        <p>Generated stories may be downloaded for personal family use but may not be resold or distributed commercially without permission.</p>
      </>
    ),
  },
  {
    title: "9. Limitation of Liability",
    content: (
      <>
        <p>Little Minds BIG Questions is provided on an "as is" basis.</p>
        <p>We are not responsible for how the generated content is interpreted or used by individuals.</p>
        <p>Users are responsible for deciding whether content is appropriate for their child.</p>
      </>
    ),
  },
  {
    title: "10. Changes to the Terms",
    content: (
      <>
        <p>These Terms and Conditions may be updated periodically.</p>
        <p>When changes are made, the updated version will be posted on this page.</p>
        <p>Continued use of the platform indicates acceptance of the updated terms.</p>
      </>
    ),
  },
];

const refundSections = [
  {
    title: "Digital Access",
    content: (
      <>
        <p>The $10 payment provides access to digital features such as private question storage, read-aloud functionality, and downloadable content.</p>
        <p>Because these are digital products delivered instantly, payments are generally non-refundable once access has been granted.</p>
        <p>If a user experiences technical problems preventing them from accessing the service, they may contact support for assistance.</p>
      </>
    ),
  },
  {
    title: "Printed Products (Future Feature)",
    content: (
      <>
        <p>If Little Minds BIG Questions offers printed books in the future, the following policies will apply:</p>
        <ul className="list-disc pl-6 space-y-1">
          <li>refunds or replacements may be offered for items that arrive damaged or defective</li>
          <li>personalised printed books may not be refundable once printing has begun</li>
          <li>shipping and delivery times may vary depending on location</li>
        </ul>
        <p>More detailed terms will be provided when printed products become available.</p>
      </>
    ),
  },
];

const TermsPage = () => {
  return (
    <div className="min-h-screen">
      <Navbar />

      {/* Hero */}
      <section className="relative overflow-hidden py-20 md:py-24 px-6 text-center">
        <FloatingBubbles count={8} />
        <div className="container max-w-3xl mx-auto relative z-10">
          <h1 className="font-display text-4xl md:text-5xl font-bold text-foreground mb-3 animate-fade-in-up">
            Terms &amp; Conditions
          </h1>
          <p className="text-lg text-muted-foreground animate-fade-in-up" style={{ animationDelay: "0.15s" }}>
            Guidelines for using Little Minds BIG Questions.
          </p>
        </div>
      </section>

      {/* Terms Sections */}
      <section className="pb-12 px-6">
        <div className="container max-w-2xl mx-auto space-y-6">
          {termsSections.map(({ title, content }) => (
            <div key={title} className="rounded-2xl bg-card border border-border p-6 md:p-8 space-y-4 text-foreground leading-relaxed">
              <h2 className="font-display text-xl md:text-2xl font-bold">{title}</h2>
              {content}
            </div>
          ))}
        </div>
      </section>

      {/* Refund Policy */}
      <section className="pb-20 px-6">
        <div className="container max-w-2xl mx-auto space-y-6">
          <h2 className="font-display text-3xl md:text-4xl font-bold text-foreground text-center pt-4 pb-2">
            Refund Policy
          </h2>

          {refundSections.map(({ title, content }) => (
            <div key={title} className="rounded-2xl bg-card border border-border p-6 md:p-8 space-y-4 text-foreground leading-relaxed">
              <h3 className="font-display text-xl md:text-2xl font-bold">{title}</h3>
              {content}
            </div>
          ))}

          {/* Contact */}
          <div className="rounded-2xl bg-card border border-border p-6 md:p-8 space-y-4 text-foreground leading-relaxed text-center">
            <h3 className="font-display text-xl md:text-2xl font-bold">Contact for Support</h3>
            <p>If you have questions about these terms or need assistance with your account, please contact:</p>
            <a
              href="mailto:hello@littlemindsbigquestions.com"
              className="inline-flex items-center gap-2 font-semibold text-primary hover:underline"
            >
              <Mail className="h-4 w-4" />
              hello@littlemindsbigquestions.com
            </a>
          </div>

          {/* Disclaimer */}
          <p className="text-xs text-muted-foreground text-center pt-4">
            Little Minds BIG Questions is a storytelling tool and is not a substitute for professional therapeutic, medical, or psychological advice.
          </p>
        </div>
      </section>

      <Footer />
    </div>
  );
};

export default TermsPage;
