INSERT INTO public.metaphor_images (filename, public_url, keywords) VALUES 
('rabbit_watercolor.png', 'https://hrxreyncncmqzcyyqnpe.supabase.co/storage/v1/object/public/metaphor-images/rabbit_watercolor.png', ARRAY['rabbit', 'animal', 'nature']),
('turtle_watercolor.png', 'https://hrxreyncncmqzcyyqnpe.supabase.co/storage/v1/object/public/metaphor-images/turtle_watercolor.png', ARRAY['turtle', 'animal', 'ocean', 'slow']),
('whale_watercolor.png', 'https://hrxreyncncmqzcyyqnpe.supabase.co/storage/v1/object/public/metaphor-images/whale_watercolor.png', ARRAY['whale', 'ocean', 'sea', 'animal']),
('owl_watercolor.png', 'https://hrxreyncncmqzcyyqnpe.supabase.co/storage/v1/object/public/metaphor-images/owl_watercolor.png', ARRAY['owl', 'bird', 'night', 'wisdom']),
('bird_watercolor.png', 'https://hrxreyncncmqzcyyqnpe.supabase.co/storage/v1/object/public/metaphor-images/bird_watercolor.png', ARRAY['bird', 'flight', 'sky']),
('stars_watercolor.png', 'https://hrxreyncncmqzcyyqnpe.supabase.co/storage/v1/object/public/metaphor-images/stars_watercolor.png', ARRAY['stars', 'night', 'space', 'sky']),
('moon_watercolor.png', 'https://hrxreyncncmqzcyyqnpe.supabase.co/storage/v1/object/public/metaphor-images/moon_watercolor.png', ARRAY['moon', 'night', 'space', 'sky']),
('sun_watercolor.png', 'https://hrxreyncncmqzcyyqnpe.supabase.co/storage/v1/object/public/metaphor-images/sun_watercolor.png', ARRAY['sun', 'day', 'light', 'sky', 'warmth']),
('rainbow_watercolor.png', 'https://hrxreyncncmqzcyyqnpe.supabase.co/storage/v1/object/public/metaphor-images/rainbow_watercolor.png', ARRAY['rainbow', 'sky', 'color', 'hope']),
('leaf_watercolor.png', 'https://hrxreyncncmqzcyyqnpe.supabase.co/storage/v1/object/public/metaphor-images/leaf_watercolor.png', ARRAY['leaf', 'nature', 'tree', 'growth']),
('mountain_watercolor.png', 'https://hrxreyncncmqzcyyqnpe.supabase.co/storage/v1/object/public/metaphor-images/mountain_watercolor.png', ARRAY['mountain', 'nature', 'landscape', 'strength']),
('path_through_trees_watercolor.png', 'https://hrxreyncncmqzcyyqnpe.supabase.co/storage/v1/object/public/metaphor-images/path_through_trees_watercolor.png', ARRAY['path', 'journey', 'forest', 'trees', 'nature']),
('hot_air_balloon_watercolor.png', 'https://hrxreyncncmqzcyyqnpe.supabase.co/storage/v1/object/public/metaphor-images/hot_air_balloon_watercolor.png', ARRAY['balloon', 'flight', 'sky', 'adventure']),
('paper_boat_watercolor.png', 'https://hrxreyncncmqzcyyqnpe.supabase.co/storage/v1/object/public/metaphor-images/paper_boat_watercolor.png', ARRAY['boat', 'water', 'journey', 'play']),
('boat_watercolor.png', 'https://hrxreyncncmqzcyyqnpe.supabase.co/storage/v1/object/public/metaphor-images/boat_watercolor.png', ARRAY['boat', 'ocean', 'journey', 'travel']),
('galaxy_swirl_watercolor.png', 'https://hrxreyncncmqzcyyqnpe.supabase.co/storage/v1/object/public/metaphor-images/galaxy_swirl_watercolor.png', ARRAY['galaxy', 'space', 'stars', 'universe']),
('shooting_star_watercolor.png', 'https://hrxreyncncmqzcyyqnpe.supabase.co/storage/v1/object/public/metaphor-images/shooting_star_watercolor.png', ARRAY['star', 'wish', 'night', 'space']),
('comet_watercolor.png', 'https://hrxreyncncmqzcyyqnpe.supabase.co/storage/v1/object/public/metaphor-images/comet_watercolor.png', ARRAY['comet', 'space', 'speed', 'stars']),
('solar_system_swirl_watercolor.png', 'https://hrxreyncncmqzcyyqnpe.supabase.co/storage/v1/object/public/metaphor-images/solar_system_swirl_watercolor.png', ARRAY['solar system', 'space', 'planets']),
('planet_watercolor.png', 'https://hrxreyncncmqzcyyqnpe.supabase.co/storage/v1/object/public/metaphor-images/planet_watercolor.png', ARRAY['planet', 'space', 'world']);